# Generated by Django 4.2.7 on 2023-11-09 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_user_followers"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
